### ISSUE TITLE
Silent Grenades

### ISSUE THREAD

**Issue by CertainlyAria** [ChxseH/IW4x-Promod#8]
In both CoD4 Promod and IW4x without mods, grenades make a sound when they hit the ground or walls but with this mod, grenades are completely silent.

**Comment by ChxseH** [comment]
Smoke grenades do make a sound, seems to just be frags. Will take a look.

**Comment by ChxseH** [comment]
I tried poking around, here's my findings:

Removing/Renaming `weapons/mp/frag_grenade_mp` causes sounds to come back, yet we need this file (disables nade cooking)

so, there's got to be something in the mod referencing `frag_grenade_mp` and telling it not to play the sounds, yet I simply cannot find it. If you can poke around and maybe find it, a PR would be very welcome.

**Comment by CertainlyAria** [comment]
The problem is old dump files. I tried files from [this](https://github.com/FreeTheTech101/IW4-Dump-Files) and [this](https://github.com/shit-ware/IW4) dump. They didn't work and silent frag grenades were still an issue. 

I'm trying to get weapons by using zonetool but I cannot find them. I already dumped almost every zone file except maps but still there isn't any weapons dir.

**Comment by CertainlyAria** [comment]
The problem is in IW4x code as `Laupetin` pointed out in discord. IW4x has disabled loading bounce sounds. [source](https://github.com/XLabsProject/iw4x-client/blob/067ee7c5849e97ab842d1d69cfcbaf71e293f088/src/Components/Modules/Weapon.cpp#L463)
