### ISSUE TITLE
Broken main menu

### ISSUE THREAD

**Issue by CertainlyAria** [ChxseH/IW4x-Promod#9]
After navigating to `OPTIONS` then `Promod` from `Main Menu`, and then going back to `Main Menu` will break the menu. `reloadmenus` command brings back the menu.

**Comment by ChxseH** [comment]
So if I'm reading this correctly: `Main Menu>Options>Promod` then hitting esc breaks the menu? Will look at.

**Comment by ChxseH** [comment]
Fixed in 2f92d38.
